import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { SessionContext } from '@/components/contexts'
import { PageLayout } from '@/components/organisms'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Atlante Gallery',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang='en'>
            <body className={manrope.className}>{children}</body>
        </html>
    )
}

export default RootLayout
