import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionContext } from '@/components/contexts'
import { PageLayout } from '@/components/organisms'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <SessionContext>
                    <PageLayout>{children}</PageLayout>
                </SessionContext>
            </body>
        </html>
    )
}

export default RootLayout
